# Generated by Django 2.2.22 on 2021-05-12 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recepies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityIngreds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(help_text='Type your recipe here', verbose_name='Text of recipe')),
                ('cooking_time', models.PositiveIntegerField(help_text='Insert cooking time', verbose_name='Total cooking time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(through='recepies.QuantityIngreds', to='recepies.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='quantityingreds',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepies.Ingredient'),
        ),
        migrations.AddField(
            model_name='quantityingreds',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepies.Recipe'),
        ),
    ]
