# Generated by Django 2.2.22 on 2021-05-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0005_recipe_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, help_text='Find and attach your file', null=True, upload_to='recepies/staticfiles/', verbose_name='Attach a picture'),
        ),
    ]
