# Generated by Django 2.2.22 on 2021-05-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0007_auto_20210513_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, help_text='Find and attach your file', null=True, upload_to='recepies/', verbose_name='Attach a picture'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Choose tags', null=True, to='recepies.Tag', verbose_name='Tag'),
        ),
    ]
