# Generated by Django 2.2.22 on 2021-06-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0016_auto_20210531_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Choose tags', to='recepies.Tag', verbose_name='Теги'),
        ),
    ]
