# Generated by Django 2.2.22 on 2021-06-02 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0017_auto_20210602_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': "Объект избранного рецепта'", 'verbose_name_plural': 'Объекты избранных рецептов'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': "Объект подписки'", 'verbose_name_plural': 'Объекты подписок'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['title'], 'verbose_name': "Объект ингредиента'", 'verbose_name_plural': 'Объекты ингредиентов'},
        ),
        migrations.AlterModelOptions(
            name='quantityingreds',
            options={'verbose_name': "Объект промежуточной модели ингредиентов'", 'verbose_name_plural': 'Объекты промежуточной модели ингредиентов'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date'], 'verbose_name': "Объект рецепта'", 'verbose_name_plural': 'Объекты рецептов'},
        ),
        migrations.AlterModelOptions(
            name='shopinglist',
            options={'verbose_name': "Объект списка покупок'", 'verbose_name_plural': 'Объекты списков покупок'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': "Объект тега'", 'verbose_name_plural': 'Объекты тегов'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='recepies.Recipe', verbose_name='Любимый рецепт'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Интересный автор'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='quantityingreds',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantityingred', to='recepies.Ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='quantityingreds',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='quantityingreds',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantityingred', to='recepies.Recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, help_text='Загрузите файл с картинкой', null=True, upload_to='recepies/', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(help_text='Напишите здесь свой рецепт', verbose_name='Описание рецепта'),
        ),
        migrations.AlterField(
            model_name='shopinglist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoping', to='recepies.Recipe', verbose_name='Рецепт купить'),
        ),
        migrations.AlterField(
            model_name='shopinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoping', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Тег'),
        ),
    ]
